"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18 10:41:52.019267
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SERVICE', 'SYSTEM', name='actortype', native_enum=False, length=20), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('runner_nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DRAINING', name='runnerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('current_jobs', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_nodes')),
    sa.UniqueConstraint('name', name=op.f('uq_runner_nodes_name'))
    )
    op.create_table('upstream_packages',
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('PYPI', name='upstreamsource', native_enum=False, length=20), nullable=False),
    sa.Column('upstream_etag', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upstream_packages')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_upstream_packages_normalized_name'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ux_users_email', 'users', ['email'], unique=True)
    op.create_index('ux_users_username', 'users', ['username'], unique=True)
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'INTERNAL', name='visibility', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_groups_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('slug', name=op.f('uq_groups_slug'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ssh_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ssh_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_keys'))
    )
    op.create_index('ix_ssh_keys_user_id', 'ssh_keys', ['user_id'], unique=False)
    op.create_index('ux_ssh_keys_fingerprint_active', 'ssh_keys', ['fingerprint'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('upstream_files',
    sa.Column('upstream_package_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('upstream_url', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('requires_python', sa.String(length=255), nullable=True),
    sa.Column('yanked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cached', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['upstream_package_id'], ['upstream_packages.id'], name=op.f('fk_upstream_files_upstream_package_id_upstream_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upstream_files')),
    sa.UniqueConstraint('upstream_package_id', 'filename', name='uq_upstream_files_package_filename')
    )
    op.create_index('ix_upstream_files_cached_access', 'upstream_files', ['cached', 'last_accessed_at'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'DEVELOPER', 'MAINTAINER', 'OWNER', name='grouprole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_members_group_user')
    )
    op.create_index('ix_group_members_user_id', 'group_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('PYTHON', 'GENERIC', name='projectlanguage', native_enum=False, length=20), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'INTERNAL', name='visibility', native_enum=False, length=20), nullable=False),
    sa.Column('default_branch', sa.String(length=100), server_default='main', nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('package_prefix_valid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('protect_default_branch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('repo_path', sa.Text(), nullable=False),
    sa.Column('repository_size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('latest_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('latest_release_version', sa.String(length=100), nullable=True),
    sa.Column('latest_release_build_id', sa.UUID(), nullable=True),
    sa.Column('last_build_status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='buildstatus', native_enum=False, length=20), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('build_counter', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_projects_group_id_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('group_id', 'slug', name='uq_projects_group_slug')
    )
    op.create_index('ux_projects_package_name_active', 'projects', ['package_name'], unique=True, postgresql_where=sa.text('archived = false AND package_name IS NOT NULL'))
    op.create_table('access_tokens',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('build_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.Enum('PERSONAL', 'SERVICE', 'RUNNER', name='tokentype', native_enum=False, length=20), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_access_tokens_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_access_tokens_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_access_tokens_token_hash'))
    )
    op.create_index('ix_access_tokens_project_id', 'access_tokens', ['project_id'], unique=False)
    op.create_index('ix_access_tokens_user_id', 'access_tokens', ['user_id'], unique=False)
    op.create_table('builds',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('PUSH', 'TAG', 'MANUAL', name='triggertype', native_enum=False, length=20), nullable=False),
    sa.Column('ref_name', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('requested_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='buildstatus', native_enum=False, length=20), nullable=False),
    sa.Column('publish_package', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('runner_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_object_key', sa.Text(), nullable=True),
    sa.Column('artifacts_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('steps_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_builds_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_builds_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runner_nodes.id'], name=op.f('fk_builds_runner_id_runner_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builds')),
    sa.UniqueConstraint('project_id', 'number', name='uq_builds_project_number')
    )
    op.create_index('ix_builds_commit_sha', 'builds', ['commit_sha'], unique=False)
    op.create_index('ix_builds_project_created', 'builds', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_builds_status', 'builds', ['status'], unique=False)
    op.create_table('git_push_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_git_push_events_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_git_push_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_push_events'))
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'DEVELOPER', 'MAINTAINER', name='projectrole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('package_versions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('package_type', sa.Enum('PYPI', name='packagetype', native_enum=False, length=20), server_default='PYPI', nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('git_tag', sa.String(length=255), nullable=True),
    sa.Column('is_yanked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('yanked_reason', sa.Text(), nullable=True),
    sa.Column('yanked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yanked_by', sa.UUID(), nullable=True),
    sa.Column('download_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_package_versions_build_id_builds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_package_versions_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['yanked_by'], ['users.id'], name=op.f('fk_package_versions_yanked_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_versions')),
    sa.UniqueConstraint('package_type', 'normalized_name', 'version', name='uq_package_versions_type_name_version')
    )
    op.create_index('ix_package_versions_normalized_name', 'package_versions', ['normalized_name'], unique=False)
    op.create_index('ix_package_versions_project_id', 'package_versions', ['project_id'], unique=False)
    op.create_table('package_files',
    sa.Column('package_version_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('WHEEL', 'SDIST', name='packagefiletype', native_enum=False, length=20), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('python_requires', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_version_id'], ['package_versions.id'], name=op.f('fk_package_files_package_version_id_package_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_files'))
    )
    op.create_index('ux_package_files_filename', 'package_files', ['filename'], unique=True)
    # ### end Alembic commands ###

    # Audit append-only ở cấp DB (spec mục 30): chặn UPDATE/DELETE.
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_logs_block_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs is append-only';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION audit_logs_block_mutation();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS audit_logs_block_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_package_files_filename', table_name='package_files')
    op.drop_table('package_files')
    op.drop_index('ix_package_versions_project_id', table_name='package_versions')
    op.drop_index('ix_package_versions_normalized_name', table_name='package_versions')
    op.drop_table('package_versions')
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_table('git_push_events')
    op.drop_index('ix_builds_status', table_name='builds')
    op.drop_index('ix_builds_project_created', table_name='builds')
    op.drop_index('ix_builds_commit_sha', table_name='builds')
    op.drop_table('builds')
    op.drop_index('ix_access_tokens_user_id', table_name='access_tokens')
    op.drop_index('ix_access_tokens_project_id', table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index('ux_projects_package_name_active', table_name='projects', postgresql_where=sa.text('archived = false AND package_name IS NOT NULL'))
    op.drop_table('projects')
    op.drop_index('ix_group_members_user_id', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_upstream_files_cached_access', table_name='upstream_files')
    op.drop_table('upstream_files')
    op.drop_index('ux_ssh_keys_fingerprint_active', table_name='ssh_keys', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_ssh_keys_user_id', table_name='ssh_keys')
    op.drop_table('ssh_keys')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('groups')
    op.drop_index('ux_users_username', table_name='users')
    op.drop_index('ux_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('upstream_packages')
    op.drop_table('runner_nodes')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
